<?php namespace Tests;

use Illuminate\Container\Container;
use Illuminate\Support\Facades\Facade;

abstract class TestCase extends \PHPUnit\Framework\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $app = new Container();
        $app->singleton('app', 'Illuminate\Container\Container');
        $app->bind(\Illuminate\Validation\ValidationServiceProvider::class);

        $app->alias(\Illuminate\Support\Facades\Validator::class,'Validator');
        /**
         * Set $app as FacadeApplication handler
         */
        Facade::setFacadeApplication($app);
    }

}